### ISSUE TITLE
Is it ok to use it for a files which has no scss specific syntax, only css?

### ISSUE THREAD

**Issue by jitendravyas** [morishitter/tidify#3]

**Comment by msaktype** [comment]
@jitendravyas We can use scssfmt for not only SCSS syntax of Sass but also vanilla CSS because all of vanilla CSS code are valid as SCSS one.

**Comment by msaktype** [comment]
@jitendravyas Can I close this issue?

**Comment by jitendravyas** [comment]
yes. so only valid css and valid sass will work.
