### ISSUE TITLE
How to change from spaces to tabs?

### ISSUE THREAD

**Issue by jitendravyas** [morishitter/tidify#4]

**Comment by msaktype** [comment]
@jitendravyas The answer is NO. There are no options for formatting in scssfmt. The concept of scssfmt is "simple and fast".

**Comment by jitendravyas** [comment]
is the default space or tab?

**Comment by msaktype** [comment]
scssfmt formats code as 2 spaces indent.

**Comment by jitendravyas** [comment]
I would prefer either tabs or atleast 4 spaces. Thanks.

**Comment by msaktype** [comment]
I have no plan to implement options for formatting in scssfmt. If you need it, please use [prettier](https://github.com/prettier/prettier/releases/tag/1.4.0) of [stylefmt](https://github.com/morishitter/stylefmt).

**Comment by jitendravyas** [comment]
No options are ok. can you do one more thing? along with formatting rules list, can you add which stylelint rule is equvlant of scssfmt rules so i can remove those rules from my .stylelintrc

**Comment by msaktype** [comment]
Sorry, I may not understand what you are saying. If you will use scssfmt and follow its formatting rule, you can remove all of stylelint rules about formatting.
