### ISSUE TITLE
Feature request: Return non-zero exit code when --diff identifies a diff

### ISSUE THREAD

**Issue by mtlynch** [morishitter/tidify#8]
I'm using scssfmt in my build script to make sure my Sass files are always formatted correctly.

One thing that would be nice is if it sets its exit code to non-zero when run with the `--diff` flag and it finds a diff in any file. This makes [behavior consistent](https://stackoverflow.com/questions/6971284/what-are-the-error-exit-values-for-diff) with the built-in diff utility and makes it easy for people to use it in build scripts.

Otherwise, I think the client has to parse the stdout to make sure `--diff` producted no actual diffs.

**Comment by msaktype** [comment]
@mtlynch Sorry, I'm late.

> One thing that would be nice is if it sets its exit code to non-zero when run with the --diff flag and it finds a diff in any file. This makes behavior consistent with the built-in diff utility and makes it easy for people to use it in build scripts.

Good catch 👍  I will fix it soon.

**Comment by msaktype** [comment]
This is the PR. https://github.com/morishitter/scssfmt/pull/10

**Comment by msaktype** [comment]
@mtlynch I just published v1.0.3. Please update :)

**Comment by mtlynch** [comment]
Awesome, thanks!
